config/routes.rb
Rails.application.routes.draw do
  resources :nodes
  resources :images
  resources :pictures
  
  root 'statics#index'
  

end

app/models/node.rb
class Node < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
   
   validates :title, presence: true
   validates :position, presence: true
   validates :parent, presence: true
   
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
   before_action :set_node, only: [:edit, :update, :show, :destroy]
   
   def index
      @nodes = Node.all
      @images = Image.all
   end
   
   def new
       @node = Node.new
       @parent = Node.find(params[:parent])

   end
   
   def create
      @node = Node.new(node_params)
      
      @node.parent = Node.find(params[:parent]).position
      @node.position = find_next_empty(@node.parent)
      
      if(@node.save)
          flash[:notice] = "Node was succesfully created, #{params[:parent]}"
          redirect_to node_path(@node)
      else
          render 'new'
      end
   end
    
  def show
    @images = Image.all
    
    @nodes = Node.all
    @id = Node.find(params[:id])
    @node = Node.find(params[:id])
    @parent = @node.position.chomp(".")
    @this = Node.find(params[:id])
  end
  
  def edit
    # if @node.parent.exists?
      @parent = find_node_with_position(Node.find(params[:id]).parent)
    # else
     # @parent = find_node_with_position(Node.find(params[:id]).position.chomp("."))
    #end
  end
  
  def update
    if @node.update(node_params)
      flash[:notice] = "Node was succesfully updated!\nHello.\n#{@node.content()}\t#{params[:node]}"
      redirect_to node_path(@node)
    else
      render 'new'
    end
  end
    
  def destroy
    destroy_children(@node)
    destroy_image(@node)
    @node.destroy
    flash[:notice] = "Node (and children) were succesfully destroyed!"
    redirect_to nodes_path
  end
  
  private
  
  def set_node
      @node = Node.find(params[:id])
  end
  
  def node_params
     params.require(:node).permit(:title, :content, :image) 
  end
  
  def find_next_empty(input) #string which should be the path of the parent)
    string_child = input + "."
    
    count = 0
    Node.all.each do |f|
      if f.position.index(string_child) == 0  #f.position (input) string_child (kill)
        if get_level(f.position, string_child) > count
          count = get_level(f.position, string_child)
        end
      end
    end
    
    count += 1
    
    #output = string.to_s + count.to_s
    output = input + "." + count.to_s
    return output
  end
  
  def get_level(input, kill) 
    temp = input.sub(kill,"")
    my_length = temp.index(".")
    if my_length
      return temp[0, my_length].to_i
    else
      return temp.to_i
    end
  end
  
  def find_node_with_position(input)
    nodes = Node.all
    nodes.each do |f|
      if f.position == input
        return f
      end
    end
    return Node.find(params["1"])
  end
  
  def destroy_children(input)
    Node.all.each do |f|
      if f.parent == input.position
        if has_children(f)
          destroy_children(f)
        end
        f.destroy
      end
    end
  end
  
  def destroy_image(input)
    Image.all.each do |f|
      if f.position == input.position
        f.destroy
      end
    end
  end
end

app/views/nodes/_form.html.erb
<% if @node.errors.any? %>
    <h2>The following errors prevented the node from being created</h2>
    <ul>
        <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @node, :html => { :multipart => true } do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>
    
    <p>
        <%= f.label :content %><br/>
        <%= f.text_area :content, :cols => "50", :rows => "10" %>
    </p>
    
    <p>
        <%= f.label :image %><br/>
        <%= f.file_field :image %>
    </p>
    
    <input type="hidden" name="parent" value="<%= @parent.id %>" />
    
    <p>
        <%= f.submit %>
    </p>
<% end %>

<% pos = @node.position %>
<%= link_to "Add image", { :controller => "images", :action => "new", :position => @node.position } %>


<%= link_to "Back to node listing", nodes_path %>

app/views/nodes/edit.html.erb
<h1>Edit a Node</h1>

<%= render 'form' %>

app/views/nodes/index.html.erb
<style type="text/css">
  td, th {
    padding: 5px;
  }
</style>

<h1>Listing All Nodes</h1>
<p>
  <% bob = @nodes.find(1) %>
  <%= link_to "Create a new node", { :controller => "nodes", :action => "new", :parent => bob } %>
</p>

<table>
  <tr>
    <th>Select Options:</th>
    <th>Content</th>
    <th>Position</th>
  </tr>
  <% @nodes.each do |f| %>
    <tr>
      <td><%= f.title %></td>
      <td><%= f.content %></td>
      <td><%= f.position %></td>
      <td><%= link_to "Edit", { :controller => "nodes", :action => "edit", :id => f, :parent => f.id } %></td>
      <td><%= link_to "Show", node_path(f) %></td>
      <td><%= link_to "Destroy", node_path(f), method: :delete, data: {confirm: "Are you sure?"}%></td>
    </tr>
  <% end %>
</table>

app/views/nodes/new.html.erb
<h1>Create a Node</h1>

<%= render 'form' %>

app/views/nodes/show.html.erb
<style type="text/css">
  td, th {
    padding: 5px;
  }
</style>

<% parent = @id.position %>
<% variable = "" %>

<% while parent.include? "." %>
  <% variable += parent[0 .. parent.index(".")] %>
  <% parent = parent[parent.index(".") + 1 .. (parent.length - 1)] %>
<% end %>

<% variable = variable.chomp(".") %>

<% @nodes.each do |f| %>
  <% if f.position == variable %>
    <%= link_to "Back to #{f.title}", {:controller => "nodes", :action => "show", :id => f } %>
  <% end %>
<% end %>

<h1>Showing selected node</h1>

<p>Title: <%= @node.title %></p>
<p>content: <%= @node.content %></p>

<% if @node.image.exists? %>
  <%= image_tag @node.image.url %>
<% end %>
<table>
  <tr>
    <th>Select Options:</th>
    <th>Content</th>
    <th>Position</th>
  </tr>
  <% string = @node.position.to_s + "." %>
  <% @nodes.each do |f| %>
    <% stringTwo = f.position %>
    <% if f.parent == @node.position %>
      <tr>
        <td><%= f.title %></td>
        <td><%= f.content %></td>
        <td><%= f.position %></td>
        <td><%= link_to "Edit", edit_node_path(f) %></td>
        <td><%= link_to "Show", node_path(f) %></td>
        <td><%= link_to "Destroy", node_path(f), method: :delete, data: {confirm: "Are you sure?"}%></td>
    </tr>
    <% end %>
  <% end %>
</table>

<table>
  <tr>
    <th>Images</th>
  </tr>
  <% @images.each do |f| %>
    <% if f.position == @node.position %>
      <tr>
        <td><%= f.title %></td>
        <td><%= f.content %></td>
        <td><%= image_tag f.img.url %></td>
      </tr>
    <% end %>
  <% end %>
</table>


<%= link_to "Edit this node", edit_node_path(@node) %>
<%= link_to "Back to node listing", nodes_path %>
<%= link_to "Create node", { :controller => "nodes", :action => "new", :parent => @node.id }  %>