config/routes.rb
Rails.application.routes.draw do
  resources :nodes
  resources :images
  resources :pictures
  
  root 'statics#index'
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :show, :destroy]
  
  def index
    @pictures = Picture.all
  end
  
  def new
    @picture = Picture.new
    @position = params[:position]
  end
  
  def create
    @picture = Picture.new(picture_params)
    
    @picture.position = params[:position]
    
    if(@picture.save)
      # flash stuff
      flash[:notice] = "Picture was sucesfully saved."
      redirect_to node_path(find_node_with_position(@picture.position))
    else
      render 'new'
    end
  end
  
  def show
    @pictures = Picture.all
  end
  
  def edit
    # blank
  end
  
  def update
    if @picture.update(picture_params)
      flash[:notice] = "Picture was succesfully updated!"
      redirect_to node_path(find_node_with_position(@picture.position))
    else
      render 'new'
    end
  end
  
  def destroy
    @picture.destroy
    flash[:notice] = "Picture was succesfully destroyed!"
    redirect_to nodes_path
  end
  
  private
  
  def set_picture
    @picture = Picture.find(params[:id])
  end
  
  def picture_params
    params.require(:picture).permit(:image)
  end
  
  def find_node_with_position(input)
    nodes = Node.all
    nodes.each do |f|
      if f.position == input
        return f
      end
    end
    return Node.find(params["1"])
  end
end

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <h2>The following errors occured.</h2>
  <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @picture, :html => { :multipart => true } do |f| %>
  
  <%= f.label :image %><br/>
  <%= f.file_field :image %>
  
  <input type="hidden" name="position" value="<%= @position %>" />
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to node listing", nodes_path %>

app/views/pictures/edit.html.erb
<h1>Edit picture</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>picture Index</h1>

<table>
    <tr>
        <th>Image:</th>
        <th>Position:</th>
    </tr>
    <% @pictures.each do |f| %>
        <tr>
            <td><%= image_tag f.image.url %></td>
            <td><%= f.position %></td>
            <td><%= link_to "Edit", { :controller => "pictures", :action => "edit", :id => f } %></td>
            <td><%= link_to "Show", picture_path(f) %></td>
            <td><%= link_to "Destroy", picture_path(f), method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
    <% end %>
</table>

app/views/pictures/new.html.erb
<h1>Create picture</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<%= image_tag @picture.image.url %>
<%= link_to "pictures", pictures_path %>
<%= link_to "Parent Node", node_path(find_node_with_position(@media.position).id)