config/routes.rb
Rails.application.routes.draw do
  resources :nodes
  resources :images
  resources :pictures
  
  root 'statics#index'
  

end

app/models/image.rb
class Image < ActiveRecord::Base
   has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
   
   validates :position, presence: true
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [:edit, :update, :show, :destroy]
    
    def index
        @images = Image.all
    end
    
    def new
        @image = Image.new
        @position = params[:position]
        @image.position = params[:position]
    end
    
    def create
        @image = Image.new(image_params)
        @image.position = params[:position]
        
        if(@image.save)
            flash[:notice] = "Image was succesfully created!"
            redirect_to node_path(find_node_with_position(@image.position))
        else
            render 'new'
        end
    end
    
    def show
        @images = Image.all
        
    end
    
    def edit

    end
    
    def update
        if(@image.save)
            flash[:notice] = "Image was succesfully created!"
            redirect_to node_path()
        else
            render 'new'
        end
    end
    
    def delete
        @image.destroy
        redirect_to images_path
    end
    
    private
    
    def set_image
        @image = Image.find(params[:id])
    end
    
    def image_params
        params.require(:image).permit(:img, :title, :content)
    end
    
    def find_node_with_position(input)
        print "LOOK HERE. INPUT = #{input}"
        
        @nodes = Node.all
        @nodes.each do |f|
          print "INPUT: #{input}\t\tf.position: #{f.position}"
          if f.position == input
            print "Found."
            return f
          end
        end
        
        print "Failed to find node w/ position"
        return Node.find(params["1"])
    end
end

app/views/images/_form.html.erb
<% if @image.errors.any? %>
    <h2>The following errors prevented the image from being created</h2>
    <ul>
        <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @image, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </p>
  
  <p>
    <%= f.label :img %>
    <%= f.file_field :img %>
  </p>
  
  
  
  <input type="hidden" name="position" value="<%= params[:position] %>" />
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

<%= link_to "Back to all images", images_path %>
<%= link_to "Back to all nodes", nodes_path %>

app/views/images/edit.html.erb
<h1>Edit Image</h1>

<%= render 'form' %>

app/views/images/index.html.erb
<h1>Listing all Images</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Image</th>
    <th>Position</th>
  </tr>
  <%= @images.each do |f| %>
    <tr>
      <td><%= f.title %></td>
      <td><%= f.content %></td>
      <td><%= image_tag f.img.url %></td>
      <td><%= f.position %></td>
    </tr>
  <% end %>
</table>

app/views/images/new.html.erb
<h1>Create new Image</h1>

<%= render 'form' %>

app/views/images/show.html.erb
<%= link_to "Parent node: #{@image.position}", node_path(find_node_with_position(@image.position)) %>

<h1>Showing Image</h1>

<p>Title: <%= @image.title %></p>
<p>Content: <%= @image.content %></p>
<%= image_tag @image.img.url %>

<%= link_to "Images Index", images_path %>